# Schema for the panels display variant plugin.
display_variant.plugin.panels_variant:
  type: ctools.block_display_variant
  label: 'Panels display variant'
  mapping:
    page_title:
      type: label
      label: 'Page title'
    layout:
      type: string
      label: Layout
    layout_settings:
      type: layout_plugin.settings.[%parent.layout]
      label: Layout settings
    builder:
      type: string
      label: Builder
    storage_type:
      type: string
      label: Storage type
    storage_id:
      type: string
      label: Storage Id

# Base schema for display config entities.
panels.display_base:
  type: config_entity
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Access Condition'
    parameters:
      type: sequence
      label: Parameter context list
      sequence:
        - type: mapping
          label: Parameter context
          mapping:
            machine_name:
              type: string
              label: 'Machine-readable name'
            label:
              type: label
              label: 'Label of the context'
            type:
              type: string
              label: 'Context type'

# Schema for the display_variant config entity.
panels.display_variant.*:
  type: config_entity
  label: 'Display variant configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    variant:
      type: string
      label: 'Display variant'
    variant_settings:
      type: display_variant.plugin.[%parent.variant]
    display_entity_type:
      type: string
      label: 'Parent entity type'
    display_entity_id:
      type: string
      label: 'Parent entity id'
    selection_criteria:
      type: sequence
      label: 'Selection criteria'
      sequence:
        - type: condition.plugin.[id]
          label: 'Selection condition'
    selection_logic:
      type: string
      label: 'Selection logic'
    static_context:
      type: sequence
      label: Static context list
      sequence:
        - type: mapping
          label: 'Static context'
          mapping:
            label:
              type: label
              label: 'Label of the context'
            type:
              type: string
              label: 'Context type'
            value:
              type: string
              label: 'Context value'
